# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: ecila
email: your-email@domain.com
author: Alice Eldridge
description: > # "soundscape composition cello research experimental"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/alicealicealice
  - title: github
    url: https://github.com/ecila
  - title: linkedin
    url: 
